return {
    { item = "Nitron Fuel", quantity = 10000 },
    { item = "Silicon Scrap", quantity = 1000 },
    { item = "Warp Cell", quantity = 100 },

    { item = "Glossy gray carbon fiber", quantity = 720 },
    { item = "Luminescent Lime Glass", quantity = 1 },

    { item = "Anti-Gravity Pulsor m", quantity = 6 },
    { item = "Anti-Gravity Generator s", quantity = 1 },

    { item = "Transfer Unit l", quantity = 2 },
    { item = "Basic Container s", quantity = 2 },
    { item = "Basic Container m", quantity = 2 },

    { item = "Wing m", quantity = 10 },
    { item = "Aileron m", quantity = 10 },
    { item = "Compact Aileron m", quantity = 10 },
    { item = "Stabilizer m", quantity = 2 },
    { item = "Stabilizer l", quantity = 2 },

    { item = "Container Hub xs", quantity = 2 },
    { item = "Remote Controller xs", quantity = 2 },
    { item = "Command seat controller s", quantity = 2 },

    { item = "Advanced Safe Space Engine m", quantity = 4 },
    { item = "Advanced Freight Space Engine l", quantity = 3 },
    { item = "Basic Atmospheric Engine l", quantity = 20 },
    { item = "Atmospheric Airbrake l", quantity = 20 },
    { item = "Adjustor l", quantity = 48 },
    { item = "Adjustor s", quantity = 48 },
    { item = "Retro-rocket Brake l", quantity = 50 },
    { item = "Basic Vertical Booster l", quantity = 10 },
    { item = "Basic Flat Hover Engine l", quantity = 10 },
    { item = "Basic Space Engine l", quantity = 10 },
    { item = "Basic Space Engine xl", quantity = 10 },
    { item = "Space Fuel Tank l", quantity = 4 },
    { item = "Atmospheric Fuel Tank l", quantity = 4 },

    { item = "Dynamic Core Unit m", quantity = 1 },
    { item = "Dynamic Core Unit l", quantity = 1 },
    { item = "Static Core Unit l", quantity = 1 },
    { item = "Static Core Unit xs", quantity = 1 },

    { item = "Basic Mining Unit l", quantity = 4 },
    { item = "Uncommon Mining Unit l", quantity = 1 },
    { item = "Advanced Mining Unit l", quantity = 1 },
    { item = "Rare Mining Unit l", quantity = 1 },

    { item = "Programming board xs", quantity = 10 },
    { item = "Territory Scanner xl", quantity = 1 },
    { item = "Deep Space Asteroid Tracker xl", quantity = 1 },
    { item = "Dynamic Core Unit s", quantity = 1 },
    { item = "Basic Space Engine m", quantity = 5 },
    { item = "Basic Atmospheric Engine m", quantity = 2 },
    { item = "Basic Atmospheric Engine s", quantity = 5 },
    { item = "Atmospheric Airbrake m", quantity = 5 },
    { item = "Space Fuel Tank xs", quantity = 1 },
    { item = "Space Fuel Tank m", quantity = 1 },
    { item = "Emergency controller xs", quantity = 1 },
    { item = "Gyroscope xs", quantity = 1 },
    { item = "Adjustor m", quantity = 15 },
    { item = "Atmospheric Fuel Tank m", quantity = 1 },
    { item = "Atmospheric Radar s", quantity = 3 },
    { item = "Bagged Plant A s", quantity = 1 },
    { item = "Bagged Plant B s", quantity = 1 },
    { item = "Plant Case E s", quantity = 1 },
    { item = "Basic Container l", quantity = 4 },
    { item = "Basic Vertical Booster m", quantity = 2 },
    { item = "Basic Vertical Booster s", quantity = 6 },
    { item = "Chair surface s", quantity = 5 },
    { item = "Full Shelf s", quantity = 1 },
    { item = "Compact Aileron s", quantity = 10 },
    { item = "Databank xs", quantity = 10 },
    { item = "Gunner Module s", quantity = 1 },
    { item = "Retro-rocket Brake m", quantity = 5 },
    { item = "Screen m", quantity = 1 },
    { item = "Screen s", quantity = 1 },
    { item = "Sink unit", quantity = 1 },
    { item = "Sliding Door s", quantity = 2 },
    { item = "Space Radar s", quantity = 2 },
    { item = "Surrogate VR Station m", quantity = 1 },
    { item = "Surrogate Pod Station m", quantity = 1 },
    { item = "Suspended Fruit Plant s", quantity = 1 },
    { item = "Toilet unit A s", quantity = 1 },
    { item = "Transparent Screen s", quantity = 7 },
    { item = "Transparent Screen xs", quantity = 2 },
    { item = "Vertical Light s", quantity = 9 },
    { item = "Uncommon Military Atmospheric Engine l", quantity = 2 },
    { item = "Uncommon Military Space Engine m", quantity = 4 },
    
    { item = "Advanced Military Atmospheric Engine xs", quantity = 2 },
    { item = "Advanced Military Hover Engine s", quantity = 1 },

    { item = "Pure Silicon", quantity = 20000 },
    { item = "Pure Iron", quantity = 20000 },
    { item = "Pure Aluminium", quantity = 20000 },
    { item = "Pure Carbon", quantity = 20000 },
    { item = "Pure Calcium", quantity = 1000 },
    { item = "Pure Chromium", quantity = 1000 },
    { item = "Pure Copper", quantity = 1000 },
    { item = "Pure Sodium", quantity = 1000 },
    { item = "Pure Sulfur", quantity = 1000 },
    { item = "Pure Silver", quantity = 1000 },
    { item = "Pure Lithium", quantity = 1000 },
    { item = "Pure Nickel", quantity = 1000 },
    { item = "Pure Fluorine", quantity = 1000 },
}
